# Generated by Django 5.0.6 on 2024-06-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('battery_health', models.IntegerField()),
                ('colour', models.CharField(choices=[('Black', 'Black'), ('Blue', 'Blue'), ('Green', 'Green'), ('Yellow', 'Yellow'), ('Black Titanium', 'Black Titanium'), ('Blue Titanium', 'Blue Titanium'), ('White Titanium', 'White Titanium'), ('Natural Titanium', 'Natural Titanium'), ('Midnight', 'Midnight'), ('Starlight', 'Starlight'), ('Purple', 'Purple'), ('Red', 'Red'), ('Space Black', 'Space Black'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Deep Purple', 'Deep Purple'), ('Pink', 'Pink'), ('Graphite', 'Graphite'), ('Sierra Blue', 'Sierra Blue'), ('Alpine Green', 'Alpine Green')], max_length=50)),
                ('images', models.ImageField(upload_to='phone_images/')),
                ('storage_capacity', models.CharField(choices=[('64 GB', '64 GB'), ('128 GB', '128 GB'), ('256 GB', '256 GB'), ('512 GB', '512 GB'), ('1 TB', '1 TB')], max_length=50)),
                ('description', models.TextField()),
                ('quantity', models.IntegerField()),
                ('location', models.CharField(choices=[('Ottapalam', 'Ottapalam'), ('Cherupulasseri', 'Cherupulasseri'), ('Perintalmanna', 'Perintalmanna')], max_length=50)),
            ],
        ),
    ]
